### ISSUE TITLE
Help with Mandrill Settings in CiviCRM

### ISSUE THREAD

**Issue by AlysonE** [JMAConsulting/biz.jmaconsulting.mte#101]
I need help figuring out what I have wrong in my Civi settings that are preventing the test email from being sent when I have set up the Mandrill Smtp Settings according to the instructions here: [https://github.com/JMAConsulting/biz.jmaconsulting.mte/blob/2.0/README.md]
The error message: Your SMTP settings are incorrect. No test mail has been sent.
This is probably related to a problem in your Outbound Email Settings (Administer CiviCRM » System Settings » Outbound Email), OR the FROM email address specifically configured for your contribution page or event. Possible causes are:
Your SMTP Username or Password are incorrect.
Your SMTP Server (machine) name is incorrect.
You need to use a Port other than the default port 25 in your environment.
Your SMTP server is just not responding right now (it is down for some reason).
The FROM Email Address configured for this feature may not be a valid sender based on your email service provider rules.
I've tried everything I can think of and I am wondering if I need to reconfigure or disable the CiviMail component to get Mandrill to work.
Thanks!

**Comment by JoeMurray** [comment]
I'm sorry to hear about your troubles. My initial guess is that this is some small typo or misunderstanding about what to put in a particular field, as there aren't other reports similar to yours.

Could you try to test the basic SMTP outbound emailing without anything to do with Mandrill? To do this, 
1. At Administer CiviCRM » System Settings » Outbound Email choose mail(), then click Save and Send Test Email button. 
2. Once 1 is working, try to send a test CiviMail using the same From Email address used in your test above.

If both of those work fine, please follow the instructions for setup of Mandrill extension again, paying particular attention to using the username and password that you used to create your **Mandrill** account. 

Could you also report back with your CMS and its version number, as well as the CiviCRM version, and confirm that you are running the 2.0 version of the biz.jmaconsulting.mte extension?

**Comment by AlysonE** [comment]
Dear Joe,
Thank you so much for taking the time to work with me on this. I have
successfully completed steps one and two above. I then went back through
the instructions, re-entered the information, and still get the same error
message. I'm wondering if I have the wrong extension installed since your
instructions refer to Mandrill Email.
My CMS is WordPress 4.4.2, Mandrill Transactional Emails version 2, and
CiviCRM version 4.6.10

Alyson

**Comment by JoeMurray** [comment]
Heh @AlysonE : by Mandrill extension I meant this one named Mandrill Transactional Emails.

Could we schedule a Skype session so we can screen share? What's your time zone? I'm in Eastern Time Zone, and my developers who I would like to assign this to are on India Time in Mumbai but work late into the evenings there.

**Comment by AlysonE** [comment]
I am in the Eastern time zone, too. Thanks!

Alyson Earl
Executive Director
Horn Farm Center for Agricultural Education
4945 Horn Road
York, PA 17406
717.757.6441
http://hornfarmcenter.org
executivedirector@hornfarmcenter.org

**Comment by JoeMurray** [comment]
Edsel, could you propose a time to meet Alyson and help her configure MTE in the next few days? Thx.

**Comment by Edzelopez** [comment]
Sure, Joe. @AlysonE I have mailed you on executivedirector@hornfarmcenter.org

**Comment by JoeMurray** [comment]
Issue resolved by @AlysonE using port 2525 per https://mandrill.zendesk.com/hc/en-us/articles/205582167-What-SMTP-ports-can-I-use- due to conflicts on port 25 and 587.
