### ISSUE TITLE
SQL error on install: "Could not find the SQL file."

### ISSUE THREAD

**Issue by xurizaemon** [JMAConsulting/biz.jmaconsulting.mte#107]
Currently master version of this ext fails on install with "Could not find the SQL file." This is because it uses CRM_Utils_File::sourceSQLFile() but passes an SQL string rather than path to SQL file.

I see from the README that the extension is discontinued, so leaving this (and #106) here for some future maintainer.

**Comment by pradpnayak** [comment]
Thanks @xurizaemon .
