### ISSUE TITLE
civicrm_activity table filling up with Mandrill activities

### ISSUE THREAD

**Issue by m4olivei** [JMAConsulting/biz.jmaconsulting.mte#26]
Hello,

I got a notice from our webhost that our space was almost completely used up.  On further investigation, it looks like the culprit is the civicrm_activity table, taking up over 2GB of disk space.  Looking into the rows in there, the majority are activity_type_id 55, 56, and 57, which I figured out were: "Mandrill Email Sent", "Mandrill Email Open"
and "Mandrill Email Click" respectively.  Looks like what is really adding up is the details column, which stores a copy of the entire email every time.  Is there anyway to either avoid logging an activity for each of these events or avoid storing the details for these events?

Using:
Drupal 7.25
CiviCRM 4.3.5
Mandrill Transactional Emails v1.2

Thanks!
Matt

**Comment by xurizaemon** [comment]
Over in #110 there's some WIP to make this a configurable option ...
