### ISSUE TITLE
Wordpress/ CiviCRM 4.5.0 install/uninstall error

### ISSUE THREAD

**Issue by JoeMurray** [JMAConsulting/biz.jmaconsulting.mte#74]
A l l i s o n W o o l b e r t emailed:

I’m having some trouble with the installation of the extension.  I’m using Wordpress with Civicrm 4.5.0 at this point.  I keep getting a DB Error when trying to install.  I’ve used the uninstall sql script but it seems to still be having issues.
 
The extension never reaches a full installation.  Do you have a manual removal instruction so I can try again?

**Comment by johnhendersonclark** [comment]
Hi, Joe, I'm looking at this too for Allison. We're in the middle of a big campaign, so any help getting this working is welcomed. I've done test emails and they went through. That I take it is just using the SMTP settings.

**Comment by JoeMurray** [comment]
I'll have Pradeep work with you. Could you provide detailed text of the error messages you are getting on uninstall and install? They'll help us identify what the problem is/what state your instance's database is in. Thanks.

**Comment by pradpnayak** [comment]
@johnhendersonclark can you please provide me error message what you got during un-install/install of extensions or could paste error from Config.log file of civicrm

**Comment by pradpnayak** [comment]
@johnhendersonclark : Are you still facing the same problem?
 I tried installing/uninstalling/enable/disabling the extension with Wordpress 4.1 and CiviCRM 4.5.0 and MTE 1.5. I didn't get any error.

**Comment by pradpnayak** [comment]
@johnhendersonclark : Are you still facing the same problem?

**Comment by pradpnayak** [comment]
Closing this since could not replicate the error
