### ISSUE TITLE
Unable to send test message

### ISSUE THREAD

**Issue by JSProffitt** [JMAConsulting/biz.jmaconsulting.mte#79]
Received the following error in Civi 4.5.5 / J 3.4.0 when trying to send a test message. It does seem to be related more to Civi core, but would still affect the extension as well.

An error occurred when CiviCRM attempted to send an email (via SMTP). If you received this error after submitting on online contribution or event registration - the transaction was completed, but we were unable to send the email receipt.
The mail library returned the following error message:
Failed to connect to smtp.mandrillapp.com:587 [SMTP: Failed to connect socket: Connection timed out (code: -1, response: )]
This is probably related to a problem in your Outbound Email Settings (Administer CiviCRM » System Settings » Outbound Email), OR the FROM email address specifically configured for your contribution page or event. Possible causes are:
Your SMTP Username or Password are incorrect.
Your SMTP Server (machine) name is incorrect.
You need to use a Port other than the default port 25 in your environment.
Your SMTP server is just not responding right now (it is down for some reason).
The FROM Email Address configured for this feature may not be a valid sender based on your email service provider rules.

**Comment by JoeMurray** [comment]
Could you send me an email (joe dot murray at jmaconsulting dot biz) with your Mandrill account and paasword so I can test it, or perhaps we can do a skype session. Between 9 and 11am tomorrow would be best.

**Comment by JoeMurray** [comment]
Jeremy determined (with a little help from me but mainly with help from his ISP) that his ISP had outbound SMTP blocked by default. They were happy to turn it on for him once requested.
