### ISSUE TITLE
Undefined index: html in .../biz.jmaconsulting.mte/mte.php on line 243

### ISSUE THREAD

**Issue by tabletguy** [JMAConsulting/biz.jmaconsulting.mte#81]
Version 1.5 installed on Joomla 2.5.28 with CiviCRM 4.6 (also had blank page under 4.5.current but didn't confirm the actual error messages).

Full message (with Show Development Error): Undefined index: html in /home/<mysite>/public_html/main/media/civicrm/custom_ext/biz.jmaconsulting.mte/mte.php on line 243

The "Search Contacts" menu item suddenly has started showing a blank screen when selected. Custom search using the same criteria (a last name, for example) works correctly.

Turning off GZip compression and then enabling either Maximum or Development error reporting gave the following messages:
===========================
Strict Standards: Declaration of JCacheControllerPage::store() should be compatible with JCacheController::store($data, $id, $group = NULL) in /home/<mysite>/public_html/main/libraries/joomla/cache/controller/page.php on line 199

Notice: Undefined index: html in /home/<mysite>/public_html/main/media/civicrm/custom_ext/biz.jmaconsulting.mte/mte.php on line 243

Strict Standards: Non-static method PEAR::raiseError() should not be called statically, assuming $this from incompatible context in /home/<mysite>/public_html/main/administrator/components/com_civicrm/civicrm/packages/Net/SMTP.php on line 375

Strict Standards: Non-static method PEAR::raiseError() should not be called statically, assuming $this from incompatible context in /home/<mysite>/public_html/main/administrator/components/com_civicrm/civicrm/packages/Mail/smtp.php on line 389
============================

**Comment by pradpnayak** [comment]
Fixed at PR https://github.com/JMAConsulting/biz.jmaconsulting.mte/pull/77 and will be available for 2.0 version
