### ISSUE TITLE
Mandrill 1.5 does not list CiviCRM 4.6 as supported in Joomla

### ISSUE THREAD

**Issue by tabletguy** [JMAConsulting/biz.jmaconsulting.mte#86]
I see that there is a version 2.0 released, but nothing shows up in CiviCRM Extensions. I have installed version 1.5 with CiviCRM 4.6.3 and Joomla 3.4.1 on Apache 2.6.xxxx

 * Installed version 1.5 doesn't list CiviCRM 4.6 (really minor but perhaps means it won't upgrade?)
 * It isn't showing version 2.0 as available

Also, there's no instructions on the readme for updating/upgrading. Hopefully that's because it's supposed to be a simple "click to update"?

**Comment by tabletguy** [comment]
When will this be ready to install in Joomla 3.4.1 to replace Mandril 1.5? Any idea?

**Comment by JoeMurray** [comment]
Hmm. I just checked and the demo Joomla site does list the 2.0 version for initial install: 
http://joomla.demo.civicrm.org/administrator/?option=com_civicrm&task=civicrm/admin/extensions&reset=1

**Comment by tabletguy** [comment]
They are running 4.6.0, not 4.6.3 (if that matters). I get "No Extensions Available" 
![noextensionsavailable](https://cloud.githubusercontent.com/assets/2747867/8065706/d7c8306e-0ea8-11e5-974c-8566fe304d88.jpg)

The link on the above goes here, fwiw: https://civicrm.org/extdir/ver=4.6.3|cms=Joomla

When I look at the available extensions tab, it doesn't show up on my site as an available update. Is this because I already have Mandrill Transactional Emails installed (version 1.5)?

Which returns me to a) Should it be showing an update available? b) What are the instructions to update manually?

Perhaps part of this is a CiviCRM issue?

Details of install. Note there's no 4.6 listed for compatibility.
![mandril_1_5_details](https://cloud.githubusercontent.com/assets/2747867/8065761/39e7b7f6-0ea9-11e5-9823-27e6535ea3bd.jpg)

**Comment by tabletguy** [comment]
Sorry, didn't upload the correct "No Extensions Available" screenshot:

![noextensionsfor_4_6](https://cloud.githubusercontent.com/assets/2747867/8065789/566918f2-0ea9-11e5-8861-dbdc0124f23b.jpg)

**Comment by JoeMurray** [comment]
When I go to the link https://civicrm.org/extdir/ver=4.6.3%7Ccms=Joomla I see the extension is there in listing as biz.jmaconsulting.mte.xml. 

There are some other reports that the extensions downloads aren't working in general for certain installs eg http://civicrm.stackexchange.com/questions/152/unable-to-install-extensions-http-redirection-error comment from yesterday. So I think the issue is with CiviCRM and extensions rather than this extension. Can you post to StackExchange about problem with No Extensions Available for this Version?

Thanks.

**Comment by tabletguy** [comment]
And when you click on the listed link for biz.jmaconsulting.mte.xml it goes to **another** listing page instead of to any actual xml file.

Posted question: https://civicrm.stackexchange.com/questions/3125/civicrm-4-6-3-cannot-update-mandrillapps-email-extension

**Comment by tabletguy** [comment]
So I think you're implying that there's no way to do a manual update?

**Comment by laryn** [comment]
Cross-reference: https://civicrm.stackexchange.com/questions/3125/civicrm-4-6-3-cannot-update-mandrillapps-email-extension
