### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by robbrandt** [JMAConsulting/biz.jmaconsulting.mte#87]
Is there a change log for version 2.0 somewhere?  I'd like to know what's different.

**Comment by JoeMurray** [comment]
No, and we should have one a sorry. The major changes were:
1. Add support for CiviMail,
2. Partly to support 1, refactor the Mandrill Administration interface out of the Outbound Email settings page into its own configuration page,
3. Fix some bugs,
4. Add automated tests.
