### ISSUE TITLE
implode(): Invalid arguments passed

### ISSUE THREAD

**Issue by tabletguy** [JMAConsulting/biz.jmaconsulting.mte#90]
Joomla 3.4.1
Mandrill Transactional Emails v2.0
Php 5.5.25
Apache

Getting many errors from MandrillApp

This is one of them.

[message] => implode(): Invalid arguments passed
[file] => /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/IDS.php
[line] => 256

Note secret zeroed out

SCRIPT_NAME:        /main/index.php
REQUEST_URI:        /main/component/civicrm/?lang=en&mandrillSecret=0000000000000000&task=civicrm/ajax/mte/callback
QUERY_STRING:       lang=en&mandrillSecret=00000000000000000&task=civicrm/ajax/mte/callback
HTTP_USER_AGENT:    Mandrill-Webhook/1.0

Please let me know at least if this is an issue with the MandrilApp extension or a general CiviCRM error

**Comment by tabletguy** [comment]
I've gotten 57 of these emails in less than 24 hours. 
I deleted the webhook from MandrillApps.com a few hours ago, and haven't seen any more of these yet. So, perhaps this message is connected with the other issue I entered about the webhook failing.

**Comment by JoeMurray** [comment]
Can you check that the CiviCRM: access AJAX API permission is set correctly for the user that is configured to do the Mandrill callback?
